
services:
  - type: web
    name: placement-tracker-backend
    runtime: python
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    plan: free
  - type: web
    name: placement-tracker-frontend
    runtime: node
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    plan: free
